### ISSUE TITLE
Video skewed

### ISSUE THREAD

**Issue by krmax44** [Dumblydore/Pontoon#23]
It appears as playing videos don't have the correct aspect ratio and therefore are skewed.

**Comment by krmax44** [comment]
I'm using a Galaxy A5 2015. 1280x720 res, Android 7.

**Comment by mkody** [comment]
I just got a OnePlus 6T and have the same problem with 16:9 videos.
My screen is a 19:9, res is 1080x2280 (or 1080x2340 w/ notch).
