### ISSUE TITLE
Can't not login

### ISSUE THREAD

**Issue by edgan** [Dumblydore/Pontoon#28]
I can't login to Floatplane via my Floatplane account. Might it be a problem with having 2FA enabled? I can login successfully through the browser on the same device.

Version:
0.9.321

Error message:
"Something happened, Not sure what it was."

**Comment by Dumblydore** [comment]
Try this build: [Pontoon.zip](https://github.com/Dumblydore/Pontoon/files/2824690/Pontoon.zip)

**Comment by Dumblydore** [comment]
Going to close. I think this is fixed in a917f1e2450fda623bf0475625ead03345c81ded.
