### ISSUE TITLE
Toolbar icon is offcentered on ChromeOS

### ISSUE THREAD

**Issue by Chundelac** [Dumblydore/Pontoon#38]
When using the bigger version of toolbar (tablet size window) the hamburger icon is positioned incorrectly.
This only affects the current master branch build but not the store version.

Left is current master. Right is store version.
![image](https://user-images.githubusercontent.com/11510682/53097273-623f0180-3521-11e9-9835-3a1990dfc47e.png)

This issue might also affect tablets but I cannot test that myself.

**Comment by Dumblydore** [comment]
I think this should be fixed in b4a65e9dc7f1c0ba4e577976863083baa2889c83.

**Comment by Chundelac** [comment]
Can confirm, the issue is fixed. 👍
