### ISSUE TITLE
Document Gettings Started

### ISSUE THREAD

**Issue by thomasmillergb** [Dumblydore/Pontoon#52]
It would be really helpful if there was a quick starter guide and a little more documentation as project currently requires a developer to poke around the codebase into how do i get this working.

For example there is no mention of the google-services.json a quick link to firebase with a one liner about you need to create an app to get a google-services.json

There also looks like there are some nice shortcuts in the local.props where you can provide a default user and password

The project is really nice however if there was a bit more documentation probably more people might chip in as i see 3 people have fork but yet to contribute.

**Comment by Dumblydore** [comment]
This is really good feedback, I'll write some setup documentation
